### ISSUE TITLE
SSL Instructions don't work

### ISSUE THREAD

**Issue by dreamingbinary** [sentora/sentora-installers#100]
Referencing this: http://docs.sentora.org/?node=60.

After adding my own Certs and restarting, visiting https://<new host> renders a "Testing 123..." page.

Do note, [I've modified the installer to use php56 instead](https://github.com/dreamingbinary/sentora-installers/blob/installer-php56/sentora_install.sh).

**Comment by dreamingbinary** [comment]
I had to manually create a VHOST and set permissions to the directory by add contents below to file in this directory: /etc/httpd/conf.d/

```
    <VirtualHost *:443>
        ServerAdmin email@domain
        DocumentRoot "/etc/sentora/panel/"
        ServerName server1.example.com
        ErrorLog "/var/sentora/logs/sentora-error.log"
        CustomLog "/var/sentora/logs/sentora-access.log" combined
        CustomLog "/var/sentora/logs/sentora-bandwidth.log" common

        <Directory "/etc/sentora/panel/">
            Options +FollowSymLinks -Indexes
            AllowOverride All
            Require all granted
        </Directory>

        SSLEngine on
        SSLCertificateFile          "/etc/pki/tls/certs/server1.example.com.crt"
        SSLCertificateKeyFile       "/etc/pki/tls/private/server1.example.com.key"
        SSLCACertificateFile        "/etc/pki/tls/certs/ca-bundle.crt"
    </VirtualHost>
```

**Comment by MBlagui** [comment]
Check the forum we had more extended informations there and you can submit a fix for the docs.
