### ISSUE TITLE
Auto redirect to http://sentora.org/?reqp=1&reqr=

### ISSUE THREAD

**Issue by trantanpro** [sentora/sentora-installers#106]
I installed rentora on my vps.
But, when i login to admin, it is auto redirect to http://sentora.org/?reqp=1&reqr=
Let't help me :3

**Comment by Ron-e** [comment]
The website is down so the following won't work:

> bash <(curl -L -Ss http://sentora.org/install)

So try the following one:

This is install lastest stable release (1.0.3) 
> bash <(curl -L -Ss https://raw.githubusercontent.com/sentora/sentora-installers/1.0.3/sentora_install.sh)

**Comment by Ron-e** [comment]
Website is up again, it should work like normal again.

**Comment by shabbirhasan** [comment]
This is install lastest stable release (1.0.3)

bash <(curl -L -Ss https://raw.githubusercontent.com/sentora/sentora-installers/1.0.3/sentora_install.sh)

i use above but completed no any step other
