### ISSUE TITLE
Wrong ownership of installed files

### ISSUE THREAD

**Issue by TGates71** [sentora/sentora-installers#110]
With current new installs, for some reason the /etc/sentora/ files and folders are owned by root when they should be owned by apache.

**Comment by MBlagui** [comment]
@TGates71 OS you used here Ubuntu 14 ? or Centos ?

It should not cause issues here as files are 777 which on the other hand too much.

**Comment by TGates71** [comment]
CentOS is root:root, Ubuntu is apache:apache

**Comment by MBlagui** [comment]
Yep agree it's root on centos. We need to fix it even it's not having any impact

**Comment by TGates71** [comment]
Correct, fixing it will make things 'easier' by being consistent across the various platforms.
