### ISSUE TITLE
ZPanel Upgrade

### ISSUE THREAD

**Issue by CreativeTechShop** [sentora/sentora-installers#114]
Ran through the steps here https://zvps.uk/sentora/upgrade and ran into a hand full of issues as well as an apparently error free but dead site.

First the databases were never created.

I had to manually create all the senora databases and then change all the ZPanel, zpanel, Zpanel to Senora in the dump and merge it all back in.

Then is appeared that the users were not setup in mysql - I added them with their passwords. 

The most 'help' I got was an error about a missing favicon in the /etc/senora folder in my httpd log but nothing else.

**Comment by MBlagui** [comment]
Please use the forums for support:
http://forums.sentora.org/

The upgrade script was alpha and we are preparing a new one.
