### ISSUE TITLE
Installer Failure - OS not supported

### ISSUE THREAD

**Issue by iMemphisXx** [sentora/sentora-installers#116]
Hi,
I'm using Debian 8 Jessie, and upon starting the installation, I get the error "Sorry, this OS is not supported by Sentora", even though it clearly states that it supports Debian 7 and 8 on your GitHub readme.

![image](https://cloud.githubusercontent.com/assets/13424998/24767193/18773a50-1af6-11e7-860a-767d0654f9ef.png)

It seem's that it is only detecting "Linux", and not the fact that it is Debian.

Help with this would be most appreciated.
-Jonathan

**Comment by MBlagui** [comment]
the current installer don't support it while the master branch in beta may support debian.

We are still evaluating if we support debian or not.
