### ISSUE TITLE
Add support for Ubuntu 16.04 and other latest version

### ISSUE THREAD

**Issue by rizwan95** [sentora/sentora-installers#121]
Is it possible to support latest Ubuntu versions like 16.04, 16.10, 17.04, etc?

**Comment by mhrubel** [comment]
I believe this project is dead! So, don't expect anything from its developers... Also, Sentora is out-dated right now. So my recommendation is not to use this for production server :) ... Thanks.

**Comment by MBlagui** [comment]
The issue with ubuntu 16.04 is how we secure PHP. We should change the current vhosts config and opt for php-fpm instead of mod_php. We are relying heavily on Suhosin. But until now we didn't had any official support for PHP 7.

Closing the ticket but we will do our best as PHP 7 is mature now and we need to support it.

**Comment by rizwan95** [comment]
Thanks :)

**Comment by rizwan95** [comment]
@MBlagui  Do you think Sentora can be used for production?

**Comment by MBlagui** [comment]
Yes I'm doing so.

**Comment by TGates71** [comment]
I too have been using it for production for several years now.

**Comment by rizwan95** [comment]
That's great to hear. Sentora is really awesome. But is it updated frequently?

**Comment by cantalupo555** [comment]
> That's great to hear. Sentora is really awesome. But is it updated frequently?

This project is dead, unless someone "fork" it, which I find very unlikely.

**Comment by cantalupo555** [comment]
> That's great to hear. Sentora is really awesome. But is it updated frequently?

This project is dead, unless someone "fork" it, which I find very unlikely.
Some community members have managed to make Sentora compatible with php 7.0, but no one has intended to bring this change to everyone.

**Comment by TGates71** [comment]
We lost our main developers, so it's been tough. One member has been working on and testing and upgrade of Ubuntu 16 and CentOS 7 with php 7. Need to check the forums for more information.

**Comment by Dukecitysolutions** [comment]
Hello ,
In my eyes Sentora will never die. I know the Sentora team has had a lose with the original devs leaving the project. That can always hurt a project/teams momentum for development. I have been trying to get Sentora teams/devs attention about my Sentora PHP 7 upgrade script, but have had lil traction or response. To be honest not sure why. They seem hesitant to allow anyone new to be added to dev team or help with project. 

 I’m hoping to have a stable release soon of Sentora Live v1.0.3.1 soon that can be used for production/Live/commercial systems soon. We are currently in BETA state as we change/update and secure Sentora core with PHP 7 and pen test systems/modules for security issues one step at a time. The more support we get for the project the sooner it will be released. I am hoping in the end the original sentora team will accept my release and merge with original sentora code and release v1.0.4 finally as its way way past due. 

If Sentora team does not accept/respond or support my development. I will fully fork project and build a new team. That is that last resort tho. I have faith the sentora team will pull tho and Understand they need help and need help fast. Follow my project for TESTING only here->

https://github.com/Dukecitysolutions/sentora-php7-upgrade

@TGates71  @cantalupo555
