### ISSUE TITLE
Centos 7 Needed Dependencies.

### ISSUE THREAD

**Issue by JzJad** [sentora/sentora-installers#122]
Centos 7 needs proftpd and mysql when installing on a minimal os install.

yum install proftpd proftpd-mysql

Sorry don't have time to put in a request and fix it my self.

**Comment by MBlagui** [comment]
Will check but I think we already got that fixed.

M B

**Comment by Dukecitysolutions** [comment]
Sentora v2.0.0 fixed this issue. Upgrade. Closing.
