### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by kvvaradha** [sentora/sentora-installers#124]
Hello I tried your Sh  file to install sentora on AWS ubuntu 16.04. it throws following error. Help me to install it. 

![screenshot_2018-6-19 10 10 0](https://user-images.githubusercontent.com/6050780/41577190-ff3d600c-73a8-11e8-8210-c3629d19d6e3.png)

**Comment by TGates71** [comment]
We do not yet support ubuntu 16.. it uses php7 and our current security layer using suhosin is not completed for php7.

**Comment by kvvaradha** [comment]
Alright,  Leave that to to install it on Ubuntu 16.04.   I want it to install it on Ubuntu 14.04 There also i had the same issue.

Any advices to solve the 'elif unexpected' issue. ?

**Comment by TGates71** [comment]
The proper installation instructions are here: http://docs.sentora.org/?node=22
Do not use the sh file directly.

**Comment by kvvaradha** [comment]
Thank you Dude,  

How Can i contribute to sentora upgrade ?

**Comment by andykimpe** [comment]
ubuntu 14.04, 16.04 and 18.04 + debian 8 add support using php 5.6.37 and suhosin working 

https://github.com/sentora/sentora-installers/issues/125

**Comment by Dukecitysolutions** [comment]
V.2.0.1 w/PHP 7+ released. Closing.
