### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by unix4you2** [sentora/sentora-installers#128]
Hi there.
Last commit for this repo was at 2018.  **Does anybody knows if this project is deprecated?**
Thanks in advance.

**Comment by bradjtrammell** [comment]
This project is not depreciated and has a fairly large following. A new version is currently in Alpha. More information on it can be found on the Official Sentora Forums, these are available at forums.sentora.org.

**Comment by Dukecitysolutions** [comment]
Sentora is still alive!!! Closing.
