### ISSUE TITLE
Centos 7

### ISSUE THREAD

**Issue by shabbirhasan** [sentora/sentora-installers#131]
How install PHP V.7 in sentora panel ?

**Comment by bradjtrammell** [comment]
Please do not double post on the same issue...

You can, but it's not officially supported at the moment. There are ways to do it, you can review these by using the forums at forums.sentora.org.

**Comment by varun-naharia** [comment]
You have to wait for sentora 2.0 for PHP 7 support but there is an unofficial solution that you can use
https://github.com/Dukecitysolutions/sentora-php7-upgrade

**Comment by Dukecitysolutions** [comment]
Next time please use the forums. Closing.
