### ISSUE TITLE
How to install 2.0

### ISSUE THREAD

**Issue by rajeevrrs** [sentora/sentora-installers#135]
`bash <(curl -L -Ss http://sentora.org/install)`

This code will install 2.0 or 1.x?

**Comment by FernandoGarcia** [comment]
Hi!

Check the script displayed by http://sentora.org/install.

```
SENTORA_INSTALLER_VERSION="2.0.0"
SENTORA_CORE_VERSION="2.0.0"
```

Best regards.

**Comment by TGates71** [comment]
Use http://forums.sentora.org or questions and support. Thanks.
