### ISSUE TITLE
Install SENTORA version v1 in 2022

### ISSUE THREAD

**Issue by anjellito** [sentora/sentora-installers#136]
With the arrival of sentora version v2
Since we can still install v1 version for centos 7, some of us still work on Sentora v1.
Could you share the command line to install version v1

Thank you

**Comment by FernandoGarcia** [comment]
Hi!

http://sentora.org/install is an alias for latest script. It redirects to https://raw.githubusercontent.com/sentora/sentora-installers/2.0.0/sentora_install.sh

So I believe you can point the command directly to old version in this way:

bash <(curl -L -Ss https://raw.githubusercontent.com/sentora/sentora-installers/1.0.3/sentora_install.sh)

Best regards.
