### ISSUE TITLE
Master branch is not up-to-date and by default

### ISSUE THREAD

**Issue by Neustradamus** [sentora/sentora-installers#138]
Dear @sentora team,

In first, I wish you a Happy New Year!

Can you update the master branch and use it by default?
- https://github.com/sentora/sentora-installers/tree/master

Can you add all the code in master branch with historical builds?

There are several branches, it is possible to clean it?
- https://github.com/sentora/sentora-installers/branches/all

**Comment by Dukecitysolutions** [comment]
We have corrected the master default issue. Master is only for Beta testing and devs. Each branch is a stable release. No need to clean.
