### ISSUE TITLE
Add dn_target_vc varchar(255) change?

### ISSUE THREAD

**Issue by TGates71** [sentora/sentora-installers#28]
Just posting this here in case it is needed later on:
Edit: https://github.com/sentora/sentora-installers/blob/master/preconf/sentora-update/1-0-0/sql/update.sql
to include: `ALTER TABLE x_dns MODIFY dn_target_vc VARCHAR(255)`
(Expands the TXT DB field from 100 to 255)

**Comment by Dukecitysolutions** [comment]
Sentora v2.0.0 has fix for this issue. Closing.
