### ISSUE TITLE
Debian 7 Error on start installation (hostinger VPS)

### ISSUE THREAD

**Issue by mateusdemboski** [sentora/sentora-installers#30]
Hello,  
When i try install the Sentora the system return this error:
```
############################################################
#  Welcome to the Official Sentora Installer 1.0.0-beta9  #
############################################################
-e
Checking that minimal requirements are ok
Detected : Linux  2.6.32-042stab093.4  x86_64
sentora_install.sh: 60: sentora_install.sh: Syntax error: word unexpected (expecting "then")

```

Details:
O.S: Debian (clean)
Version: 7.5 (Wheezy)
VPS Provider: [Hostinger](http://hostinger.com/)

**Comment by andykimpe** [comment]
Please read before installing

http://docs.sentora.org/?node=7

debian his 7 will not work with this installer

a request was already made for debian adding 7

kandrews has planned to add to the support a bit of patience

**Comment by Caffe1neAdd1ct** [comment]
Debian 7 and 8 support has now been added to master for testing. Please test and raise a new issue is any problems occur.

**Comment by MBlagui** [comment]
seem we have issues with support as it require more testing

https://github.com/sentora/sentora-installers/issues/79
