### ISSUE TITLE
PANEL_PATH should default to /opt/sentora

### ISSUE THREAD

**Issue by cloakedcode** [sentora/sentora-installers#31]
As a sysadmin I would really appreciate it if sentora was not installed to `/etc/sentora` but rather `/opt/sentora`.

It is the linux standard that `/opt` contain third-party software, as opossed to what comes with the base distro install. See here: [/opt](http://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/opt.html).
On the other hand, `/etc` is reserved for configuration files only and should certainly not contain files that will be served through apache, `/etc/sentora/panel` for example ([/etc](http://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/etc.html) definition).

If all that's required to change the installation path is that `PANEL_PATH` be modified, this seems like a nobrainer. Unless this is outright rejected, I'll submit a PR.

**Comment by andykimpe** [comment]
for me I recommend:

/etc/sentora => for sentora configuration files
/opt/sentora => for source/compiled
/var/sentora => for sites hostdata
/var/backups/sentora => for backups
/var/log/sentora => for log
/var/mail/sentora/vmail => for mail
/var/tmp/sentora => for temp
