### ISSUE TITLE
centos error start named 

### ISSUE THREAD

**Issue by andykimpe** [sentora/sentora-installers#35]
<code>service named restart 
Stopping named: .                                          [  OK  ]
Starting named: 
Error in named configuration:
/etc/named.conf:11: expected IP match list element near ';'
                                                           [FAILED]
</code>

<code>cat /etc/named.conf</code>

<code>key "rndc-key" {
        algorithm hmac-md5;
        secret "UDvr061Ihk2iZvN0oY83rQ==";
};
# This control was present in Ubuntu and absent in CentOs.
controls {
inet 127.0.0.1 port 953
allow { 127.0.0.1; } keys { "rndc-key"; };
};
acl trusted-servers {
;
};
options {
listen-on port 53 { any; };
listen-on-v6 port 53 { any; };
allow-query { any; };
directory "/var/named";
dump-file "/var/named/data/cache_dump.db";
statistics-file "/var/named/data/named_stats.txt";
memstatistics-file "/var/named/data/named_mem_stats.txt";
recursion no;
dnssec-enable yes;
dnssec-validation yes;
dnssec-lookaside auto;
/* Path to ISC DLV key */
bindkeys-file "/etc/named.iscdlv.key";
};
logging {
channel bind_log {
file "/var/sentora/logs/bind/bind.log" versions 3 size 2m;
severity info;
print-severity yes;
print-time yes;
print-category yes;
};
channel default_debug {
file "/var/sentora/logs/bind/debug.log";
severity dynamic;
};
category default {
bind_log;
};
};
include "/etc/named.rfc1912.zones";
include "/etc/sentora/configs/bind/etc/named.conf";</code>

test regénérate configuration

<code>service named stop
Stopping named:                                            [  OK  ]</code>

<code>rm -rf /etc/named.conf /etc/rndc.conf /etc/rndc.key</code>

<code>rndc-confgen -a -r /dev/urandom</code>

<code>cat /etc/rndc.key /etc/sentora/configs/bind/named.conf > /etc/named.conf</code>

<code>cat /etc/rndc.key /etc/sentora/configs/bind/rndc.conf > /etc/rndc.conf</code>

<code>rm -f /etc/rndc.key</code>

<code>service named start 
Starting named: 
Error in named configuration:
/etc/named.conf:11: expected IP match list element near ';'
                                                           [FAILED]
</code>

propose patch

<code>service named stop
Stopping named:                                            [  OK  ]</code>

<code>mv /etc/named.conf /etc/named.conf.back</code>

<code>echo "$(sed '11d' /etc/named.conf.back)" > /etc/named.conf</code>

<code>rm -f /etc/named.conf.back</code>

<code>service named start
Starting named:                                            [  OK  ]</code>

**Comment by MBlagui** [comment]
@andykimpe centos 6?

**Comment by 5050** [comment]
done
