### ISSUE TITLE
Vagrantfile private ip issue

### ISSUE THREAD

**Issue by kk86bioinfo** [sentora/sentora-installers#40]
Vagrantfile seems download a ubuntu 14.04 box with pre-configured ip to 192.168.33.15 but the vagrant file set public IP to be 192.168.1.18. Which one to follow? I cannot access the vm after running sentosa rc2 install sh script.

**Comment by trojanspike** [comment]
You can config it as you want - the reason I put a public IP is for accessing Sentora from other devices | computers on the same network.

vagrant ssh ubunbu64 
$ ifconfig 
-> to see network conf : inet addr:192.168.1.18
It's more likely going to be 192.168.1.18

I

**Comment by trojanspike** [comment]
I've added private IP to vagrant , you can do a pull on it.
