### ISSUE TITLE
Missing requirements for Ubuntu

### ISSUE THREAD

**Issue by denysvitali** [sentora/sentora-installers#41]
Hi everyone,
I just noticed that the installer doesn't check if `cron` package is installed if the OS is Ubuntu, and neither for `ca-certificates` package (it throws errors while downloading from https if this package isn't installed).

I had problems installing the version 1.0.0 of Sentora on a new VPS that hasn't those packages: I tought they were installed by default in every version of Ubuntu, but in this VPS wasn't.
(I had no problem at all by installing the earlier version a while ago on another VPS which of course had those package installed by default)

Should we create a package requirements list or a script to check if some package is missing? I think it would be great and of course will remove hours of problem searching.

**Comment by MBlagui** [comment]
Ok but we are supposed to use ubuntu minimal install not a custom install? And cron is already there.
We are not supposed to check ALL packages but we can add a check for cron.

Notice VPS images are custom built images that might have packages missing depending on hosting company. We face some issues with them but our main focus is ISO minimal install and we test too on digital ocean.

**Comment by Caffe1neAdd1ct** [comment]
I test on netinstalls of CentOS, Ubuntu and now Debian. All zvps.uk images are from netinstall minimal with no extra options. We also needed these packages which have been added by a pull request.

**Comment by MBlagui** [comment]
On tests on digital ocean no issues over CRON but we can add it.
