### ISSUE TITLE
chattr package missing

### ISSUE THREAD

**Issue by MBlagui** [sentora/sentora-installers#43]
https://github.com/sentora/sentora-core/issues/113

seem missing from some os's

**Comment by Caffe1neAdd1ct** [comment]
Debian 7.9 and 8.* requires `e2fslibs`
CentOS 6 & 7 requires `e2fsprogs`

Adding to the installers now with an upgrade script to fix existing servers.

**Comment by Caffe1neAdd1ct** [comment]
Fixed, if you want to fix this manually please see updates in `preconf/sentora-update/1-0-4/shell/`.
