### ISSUE TITLE
Postfix users length issue

### ISSUE THREAD

**Issue by MBlagui** [sentora/sentora-installers#49]
This bug is popping up a lot and will check it again
http://forums.sentora.org/showthread.php?tid=1134

But seem we need to reduce user length.

M B

**Comment by andykimpe** [comment]
hi mehdi ovh two types of vps

cloud and clasic

it would be nice to know on what kind of vps customer encounters installation problems

**Comment by Caffe1neAdd1ct** [comment]
Fixes for existing systems added in preconf/sentora-update/1-0-4/
