### ISSUE TITLE
Installer error while installing pureftp

### ISSUE THREAD

**Issue by dsonawane** [sentora/sentora-installers#50]

**Comment by dsonawane** [comment]
I got the below error while installing sentora on centos 7.

-- Installing ProFTPD
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '48' at line 2
ln -s '/usr/lib/systemd/system/proftpd.service' '/etc/systemd/system/multi-user.target.wants/proftpd.service'

-- Installing and configuring cron tasks
Package crontabs-1.11-6.20121102git.el7.noarch already installed and latest version
You (apache) are not allowed to access to (crontab) because of pam configuration.
chmod: cannot access ‘/var/spool/cron/apache’: No such file or directory

Please help on this

**Comment by Ron-e** [comment]
Make sure you begin with a clean minimal install of CentOS before installing Sentora.
What i use to ensure is:
> yum remove -y httpd httpd-devel php php-devel php-gd php-mbstring php-intl php-mysql php-xml php-xmlrpc php-mcrypt php-imap php-pear php-mysql php-cli php-common php5-dev myself mysql dovecot-mysql MariaDB MariaDB-common MariaDB-compat MariaDB-server phpMyAdmin postfix dovecot dovecot-mysql dovecot-pigeonhole  sendmail ProFTPd proftpd proftpd-mysql vsftpd named bind bind-utils bind-libs bind9 pdns pdns-backend-mysql pdns-server pdns-server-backend-mysql webalizer crontabs

And after that:
>yum clean all

**Comment by andykimpe** [comment]
thank you to repeat the installation from a clean machine

thank you to provide the complete log file

without this information is not perssone poura check it comes to a bug in the installer or system

**Comment by Caffe1neAdd1ct** [comment]
Install on clean CentOS 7.1 minimal seems to work fine:

```
# Building suhosin
2015-09-21 12:35:53 URL:https://codeload.github.com/stefanesser/suhosin/zip/0.9.37.1 [238480/238480] -> "suhosin.zip" [1]
Installing shared extensions:     /usr/lib64/php/modules/
ln -s '/usr/lib/systemd/system/httpd.service' '/etc/systemd/system/multi-user.target.wants/httpd.service'
Job for httpd.service failed. See 'systemctl status httpd.service' and 'journalctl -xn' for details.

-- Installing ProFTPD
ln -s '/usr/lib/systemd/system/proftpd.service' '/etc/systemd/system/multi-user.target.wants/proftpd.service'

-- Installing and configuring Bind
Package 32:bind-utils-9.9.4-18.el7_1.5.x86_64 already installed and latest version
Package 32:bind-libs-9.9.4-18.el7_1.5.x86_64 already installed and latest version
wrote key file "/etc/rndc.key"
ln -s '/usr/lib/systemd/system/named.service' '/etc/systemd/system/multi-user.target.wants/named.service'

-- Installing and configuring cron tasks
Package cronie-1.4.11-13.el7.x86_64 already installed and latest version
Package crontabs-1.11-6.20121102git.el7.noarch already installed and latest version

-- Configuring phpMyAdmin

-- Configuring Roundcube

-- Configuring Webalizer
```

Please let us know how to replicate if this is encountered persistently.
