### ISSUE TITLE
Installer error

### ISSUE THREAD

**Issue by RaringM** [sentora/sentora-installers#60]
When I try to install Sentora
```(y):Accept and install, (n):Change domain or IP, (q):Quit installer? y```
at that point this error comes up
```install.sh: line 300: syntax error near unexpected token `>'
install.sh: line 300: `exec > >(tee "$logfile")'```
Which I could fix by removing the couple of lines but it disables logging to the file
I'm using Ubuntu 14.04.1

**Comment by jacobg830** [comment]
Sentora only supports Ubuntu LTS releases (12.04 and 14.04), but the installer should echo "This OS is not supported" instead of continuing with installation. Did you modify the installer?

**Comment by RaringM** [comment]
Oh... oops I meant to say Ubuntu 14.04.1, and no I did not modify the installer

**Comment by onlineth** [comment]
I am also having this issue

**Comment by andykimpe** [comment]
update 14.04.2 and test

not work try dos2unix

apt-get install dos2unix

dos2unix sentora_install.sh

./sentora_install.sh

**Comment by 5050** [comment]
There are a lot of hostings that setup modified distributions of Ubuntu. (We have had bunches of problems with crissic hostings VPS : cron disabled, package missings, etc. conducting to ugly error messages and disfunctionements). 

I wonder if it will be required to setup a database of hostings with list of change they do from default official ISO distribution....

**Comment by Caffe1neAdd1ct** [comment]
@5050 maybe we can start a thread for supported providers and maintain them into a list on the documentation website?

Closing this issue for now as it appears to be working on a clean minimal net install of ubuntu 14.04.* at the moment.
