### ISSUE TITLE
ERROR on Sentora Installation

### ISSUE THREAD

**Issue by hrace009** [sentora/sentora-installers#65]
There is an error on Sentora Install Script for CentOS 6.5 64Bit Minimal Install
<code>cat: /etc/hostname: No such file or directory
sed: -e expression #1, char 0: no previous regular expression</code>

<code>-- Installing Postfix
Package 2:postfix-2.6.6-6.el6_5.x86_64 already installed and latest version
ERROR 1071 (42000) at line 115: Specified key was too long; max key length is 1000 bytes</code>

<code># Building suhosin
wget: unable to resolve host address “codeload.github.com”
[suhosin.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of suhosin.zip or
        suhosin.zip.zip, and cannot find suhosin.zip.ZIP, period.
/dev/fd/63: line 887: cd: suhosin-0.9.37.1: No such file or directory
make: *** No rule to make target `install'.  Stop.</code>

Thats all i got this moment

**Comment by andykimpe** [comment]
thank you to provide the complete log file

without this information is not perssone poura check it comes to a bug in the installer or system

if using a vps thank you specify the virtualization type (openvz, kvm ...)

given the error I have a problem we are dealing dns networks

check file /etc/resolv.conf

**Comment by Caffe1neAdd1ct** [comment]
`/etc/hostname` should exist on CentOS 6.5, who was the provider of the server or if you installed yourself what steps did you take?

**Comment by Caffe1neAdd1ct** [comment]
Your server / install looks unable to resolve dns names and has no hostname .. going to close this for now.
