### ISSUE TITLE
Installer shows a false DNS warning

### ISSUE THREAD

**Issue by bambusoft** [sentora/sentora-installers#68]
I have two network addresses in the same eth0 interface (one for IPv4 and one for IPv6)
when the installer checks if the panel domain is already assigned in DNS sends this two messages:

OK: DNS succesfully resolves <fqdn> to <ipv4> address
WARNING: <fqdn> DNS record does not point to <ipv4>! Sentora will not be reachable from http://<fqdn>

This contradictory messages seems to be the result of this commands in the installer
dns_panel_ip=$(host "$PANEL_FQDN"|grep address|cut -d" " -f4)
..
if [[ "$dns_panel_ip" != "$PUBLIC_IP" ]]; then ...

which fails when more than one address exist as the result of host command

(Ubuntu 14.04 x64)

**Comment by Caffe1neAdd1ct** [comment]
Thanks for the bug report, i'll setup a server with two adapters and give this a test.

**Comment by MBlagui** [comment]
hmmm This setup is uncommon. BUT not notice it doesn't break install.

So low priority @5050

**Comment by Dukecitysolutions** [comment]
Uncommon setup. Closing.
