### ISSUE TITLE
Debian 7 install issue

### ISSUE THREAD

**Issue by deancb** [sentora/sentora-installers#79]
Trying to install onto a Debian 7 box, I have used the following:

`wget https://raw.githubusercontent.com/sentora/sentora-installers/master/sentora_install.sh`

When running `./sentora_install.sh` I am getting:
```
############################################################
#  Welcome to the Official Sentora Installer master  #
############################################################

Checking that minimal requirements are ok
Detected : debian  7  x86_64
Sorry, this OS is not supported by Sentora.
```

**Comment by MBlagui** [comment]
hmm this is still ALPHA.

You can disable os check manually and try to force it.

M B

**Comment by deancb** [comment]
I managed to fix this by changing line 75 from:

   `"$OS" = "Debian" && ("$VER" = "7" || "$VER" = "8" ) ]] ; then`

to

    `"$OS" = "debian" && ("$VER" = "7" || "$VER" = "8" ) ]] ; then`

**Comment by slacknux** [comment]
Exactly, it's 'debian' (not 'Debian'). It is ok in my repository.
I took a look to the manual merge by Caffe1neAdd1ct of my Debian support and he messed up some stuff. I'm going to fix them soon.

**Comment by Caffe1neAdd1ct** [comment]
Fixed apologies about that one :8ball:
