### ISSUE TITLE
Curious here...why not make a separate upgrade script?

### ISSUE THREAD

**Issue by TGates71** [sentora/sentora-installers#80]
Why integrate the upgrade into the install script? Sounds way more complicated to me and more difficult to do. No??

**Comment by MBlagui** [comment]
As I can see Kevin did that as he need the upgrade module to overwrite the config files.

For me the config files should be patched as setting new one's would bring down all the setup. This require more work and will be safer instead of rewriting all the configs.

This is my point

**Comment by TGates71** [comment]
I see. You guys need to get together and have a chat about planning it out.
