### ISSUE TITLE
Table creation error

### ISSUE THREAD

**Issue by hrace009** [sentora/sentora-installers#83]
Seems there is a little problem on sentora Installer
<code>http://sentora.org/install</code>
On the install log, i seen
<code>ERROR 1005 (HY000) at line 98: Can't create table 'sentora_postfix.vacation_notification' (errno: 150)</code>
The error showon at installaing postfix.
Overall, everything is fine, and the panel run normal, but that error really disturbing me :dancer:

**Comment by mrpinks** [comment]
I created the table manually post install::

CREATE TABLE `vacation_notification` (
  `on_vacation` varchar(255) NOT NULL,
  `notified` varchar(255) CHARACTER SET latin1 NOT NULL,
  `notified_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`on_vacation`,`notified`),
  CONSTRAINT `vacation_notification_pkey` FOREIGN KEY (`on_vacation`) REFERENCES `vacation` (`email`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Postfix Admin - Virtual Vacation Notifications';


The SQL for the postfix tables is here for Sentora:
https://github.com/sentora/sentora-installers/blob/master/preconf/sentora-install/sql/sentora_postfix.sql

**Comment by Dukecitysolutions** [comment]
Don’t see any current issues. Closing.
