### ISSUE TITLE
Installer Vagrant issues

### ISSUE THREAD

**Issue by jacobgelling** [sentora/sentora-installers#85]
I'm noticing our official installers are not Vagrant-friendly as they remove .gitignore (so nothing is ignored) and a copule other files. See https://github.com/jacobgelling/sentora-installers/blob/1.0.3/sentora_install.sh#L484-L485

Also, the phpMyAdmin config requires ```$cfg['CheckConfigurationPermissions'] = false;``` as permissions are assumed to be 777 over shared directories (/etc/sentora/panel to Vagrant's sentora-core folder) in Vagrant. Without it phpMyAdmin prevents logins.

I think it would be best to add a vagrant argument to installer which doesn't delete any core files and appends required entries to config files.

I think it may be wise to include the README.md and especially the LICENSE.md anyway, even if Vagrant isn't being used?

Anyone have any thoughts?

**Comment by MBlagui** [comment]
Vagrant issues and file will be moved into the right repos. As it's totally  independent from the installers.

I expect a clean up in installers so we focus on Install/update.

We should report issues there:
https://github.com/sentora/sentora-vagrant
