### ISSUE TITLE
SPF records being deprecated, use TXT record instead.

### ISSUE THREAD

**Issue by TGates71** [sentora/sentora-installers#86]
I found this:
https://mxtoolbox.com/problem/spf/spf-record-deprecated?page=prob_spf&action=spf:mach-hosting.com:96.114.154.163&showlogin=1&hidepitch=0&hidetoc=1

Currently I have both set on my server's DNS. Removed the SPF entry and get this warning:

```Your DNS zone has been loaded, but with errors. Some features may not work until corrected.

Please note that changes to your zone records can take up to 24 hours before they become 'live'.

Output of DNS zone checker:
zone mach-hosting.com/IN: 'mach-hosting.com' found SPF/TXT record but no SPF/SPF record found, add matching type SPF record zone domain.com/IN: loaded serial 2016010831 OK ```

**Comment by MBlagui** [comment]
http://stackoverflow.com/questions/13971324/should-we-use-spf-txt-spf-type-99-or-just-one-or-the-other

**Comment by Dukecitysolutions** [comment]
Removed from Sentora since v2.0.0. Closing
