### ISSUE TITLE
vagrant up sentora_6.4centos64 don´t work

### ISSUE THREAD

**Issue by paulvilla** [sentora/sentora-installers#88]
the command does not work
vagrant up sentora_6.4centos64

This is the message:
The machine with the name 'sentora_6.4centos64' was not found configured for
this Vagrant environment.

Also it works with other options

Other than that, I would like an installation with centos 7

**Comment by MBlagui** [comment]
All vagrant issue should be in vagrant repo's.

https://github.com/sentora/sentora-vagrant
