### ISSUE TITLE
Sentora dockerized version? 

### ISSUE THREAD

**Issue by jujes** [sentora/sentora-installers#94]
Hi, I'm looking for dockerized version of Sentora, someone can tell about that?

**Comment by bobsta63** [comment]
There is no official "dockerized" version of Sentora yet but there may be an unofficial one out in the wild somewhere!

I will look into providing one this weekend though!

**Comment by jujes** [comment]
:+1: 

> There is no official "dockerized" version of Sentora yet but there may be an unofficial one out in the wild somewhere!
> I will look into providing one this weekend though!

**Comment by MBlagui** [comment]
Check the installer it have already hidden options to allow instal without any interaction so you can easily use it in docker in few lines.
