### ISSUE TITLE
Update SOA Expire time

### ISSUE THREAD

**Issue by TGates71** [sentora/sentora-installers#95]
@MBlagui 
In: https://github.com/sentora/sentora-installers/blob/master/preconf/sentora-install/sql/sentora_core.sql#L652
Line: 652
`(61,'expire_ttl','SOA Expire TTL','86400',NULL,'Global expire TTL. Default = 86400 (1 day)','DNS Config','true'),`
Change to:
`(61,'expire_ttl','SOA Expire TTL','2419200',NULL,'Global expire TTL. Default = 2419200 (4 Weeks)','DNS Config','true'),`

Set to max (4 weeks), but should be any time between 2-4 weeks.

Also, still looking for `;expire after 1 week` to convert to: `;expire after 4 weeks` to show in zone file properly.

**Comment by MBlagui** [comment]
Why changing to 4 week ??? IT's TOO long and bad. We should stick with 1 day or 2 days. above that if you have any issue and want to change DNS the change may take up to 1 month to propagate as the DNS record could be cached for that long.
