### ISSUE TITLE
Postfix for Debian in https://github.com/sentora/sentora-installers/blob/master/sentora_install.sh

### ISSUE THREAD

**Issue by ibstelix** [sentora/sentora-installers#96]
Hi,
## the script is not handling Postfix installation for debian.
# --- Postfix

echo -e "\n-- Installing Postfix"
if [[ "$OS" = "CentOs" ]]; then
    $PACKAGE_INSTALLER postfix postfix-perl-scripts
    USR_LIB_PATH="/usr/libexec"
elif [[ "$OS" = "Ubuntu" ]]; then
    $PACKAGE_INSTALLER postfix postfix-mysql
    USR_LIB_PATH="/usr/lib"
## fi

maybe add  lines:
elif [[ "$OS" = "Debian" ]]; then
    $PACKAGE_INSTALLER postfix postfix-mysql

Best regards,

**Comment by MBlagui** [comment]
Will check it

**Comment by chidiigwe** [comment]
Hello,

I am not sure whether this is the solution to my problem. I installed Sentora on Debian 8 using this installer. 

During the installation process, as I was watching, I noticed a message that postfix main.cf and master.cf files were not created. Then the process continued and the system installed all the other applications.

So, postfix was not installed. I am not able to sent or receive emails. But everything else is working correctly.

Do you know how I can install or reinstall postfix?

Any help here will be highly appreciated.

Chidi
