### ISSUE TITLE
Customize stack option for Debian

### ISSUE THREAD

**Issue by blindpet** [sentora/sentora-installers#98]
Is there a way to customize my stack with some parameters for the installer?

Like I do not want to use Apache for anything only nginx. I would like to be able to choose between memcached and redis and so forth.

I'd also like to be able to skip mariadb if possible or choose postgresql

**Comment by TGates71** [comment]
Sentora is not designed at this time to run on nginx nor use postgresql.

**Comment by MBlagui** [comment]
memcached is not secure for shared hosting. 

Also postgreSQL is not currently supported.

**Comment by blindpet** [comment]
memcached with SASL is OK though, isn't it?

I don't use postgreSQL either but options are nice.

I didn't know the target group was shared hosting, I want to use it on my VPS with nginx, mariadb and redis
