### ISSUE TITLE
Ubuntu 16.04 support 

### ISSUE THREAD

**Issue by MBlagui** [sentora/sentora-installers#99]
Need more testing.

Also PHP 7 support and mySQL 5.7:

https://wiki.ubuntu.com/XenialXerus/ReleaseNotes

**Comment by MBlagui** [comment]
https://github.com/sektioneins/suhosin7

We can't as suhosin for PHP 7 is not available, so we need first to change security model and change sandboxing.

**Comment by u12206050** [comment]
Any update on support for ubuntu 16.04?

**Comment by MBlagui** [comment]
Did you notice my previous comment? As long there is no suhosin support we can't move on using the current setup.

**Comment by oquidave** [comment]
Hello, is there any update to this since Suhosin for PHP 7.x is now available https://github.com/sektioneins/suhosin7

**Comment by TGates71** [comment]
No, it is not...

> WARNING: THIS SOFTWARE IS PRE-ALPHA SOFTWARE. DO NOT ATTEMPT TO RUN IN PRODUCTION

**Comment by Lewis15520** [comment]
Guys it's been years now... find an alternative... I really want to be able to run php7 with sentora
